name: bloquinho
description: "Uma aplicação completa similar ao Notion - Self-Hosted Workspace"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # UI & Theming
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  phosphor_flutter: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0

  # Database & Storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Text Editing & Rich Content
  flutter_quill: ^8.4.3
  markdown: ^7.1.1
  flutter_markdown: ^0.6.18

  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path: ^1.8.3

  # Drag & Drop
  flutter_reorderable_list: ^1.3.1
  reorderables: ^0.6.0

  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9

  # Network
  http: ^1.1.0
  dio: ^5.3.2

  # Utilities
  uuid: ^4.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Real-time & Synchronization
  web_socket_channel: ^2.4.0

  # Charts & Data Visualization
  fl_chart: ^0.65.0

  # Search
  flutter_typeahead: ^4.8.0

  # Animations
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - logo.png
    - logoDark.png
    - screenshots/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
